export const SET_QUERY = 'SET_QUERY';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_SEARCH_RESULTS_SUCCESS = 'SET_SEARCH_RESULTS_SUCCESS';
export const SET_SEARCH_RESULTS_FAILURE = 'SET_SEARCH_RESULTS_FAILURE';

export const SET_IMAGES = 'SET_IMAGES';
export const RESET_IMAGES = 'RESET_IMAGES';
export const SET_IMAGES_SUCCESS = 'SET_IMAGES_SUCCESS';
export const SET_IMAGES_FAILURE = 'SET_IMAGES_FAILURE';

export const SET_LOAD_MORE = 'SET_LOAD_MORE';
export const SET_LOAD_MORE_IMAGES = 'SET_LOAD_MORE_IMAGES';

export const USER_PAGE_LIMIT = 30;
export const PHOTO_PAGE_LIMIT = 12;
